version : "3.5"
services:
  mysql:
    image: mysql:8
    container_name: cultus_mysql 
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=cultus
    volumes:
      - "./init.sql:/data/application/init.sql"
      - "./mysql:/var/lib/mysql"
  api_groups:
    depends_on:  
      - mysql
    image: ggmartinez/laravel:php-82
    container_name: cultus_groups 
    ports:
      - "8002:8000"
    volumes:
      - "./:/app"

  api_auth:
   depends_on:  
     - mysql
   image: ggmartinez/laravel:php-82
   container_name: cultus_auth 
   ports:
    - "8000:8000"
   volumes:
    - "/home/sm0ke/Desktop/Cultus/Cultus-APIdeAutenticacion:/app"